# @package task_cfg
defaults:
  - _self_

_target_: src.models.sahi.SahiPredictingConfig
model_name: yolo11n
model: null
project: null
save: True
device: cpu
mode: predict
task: predict

model_type: ultralytics
conf_threshold: 0.25
hide_conf: True
slice_height: 256
slice_width: 256
overlap_height_ratio: 0.2
overlap_width_ratio: 0.2
rect_th: 2
text_size: 0.5
hide_labels: False
image_size: 640