# Config for YOLO family
_target_: src.models.yolo.YoloModel

# argument for init of
cfg:
  ...

task_cfg:
  _target_: src.models.yolo.YoloPredictionConfig
  model_name: yolo11n
  model_path: null
  project: null
  save: True
  device: cpu
  mode: predict

  task: detect
  image_size: 640
  save_run: False
  model_task: yolo
