defaults:
  - cfg: yolo
  - model: yolo
  - task_cfg: predict
  - data: sample

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: logs
    chdir: True
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'