_target_: src.tasks.yolo.YoloTrainingConfig

model_name: yolo11n
mode: predict
task: detect

model: null
data: ${data.paths}
epoches: 100
time: null
patience: 10
batch: 1
imgsz: 640
save: True
save_period: -1
cache: True
device: mps
project: null
name: null
exist_ok: True
pretrained: True
optimizer: AdamW
seed: 0
single_cls: False
classes: null
multi_scale: False
resume: False
amp: True
fraction: 1.0
profile: False
freeze: null
lr0: 0.1
lr1: 0.01
momentum: 0.9
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 0.1
cls: 12.0
kobj: 2.0
nbs: 64
overlap_mask: True
mask_ratio: 4
dropout: 0.1
val: True
plots: False
